<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="AddFlightPage.aspx.cs" Inherits="Web_Flight_Reservation_System.AddFlightPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="CSS/Gridview.css" rel="stylesheet" />
    <link href="CSS/Button.css" rel="stylesheet" />
    <link href="CSS/Textbox.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style2 {
            border-collapse: collapse;
            margin-right: 0px;
        }
        .auto-style3 {
            margin-top: 19px;
        }
        .auto-style4 {
            width: 1329px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server" >
   <div>
       <br />
    </div>
    <div align="center" class="auto-style4">
        <asp:Label ID="lbladdflight" runat="server" Text="Add Flight Details" BorderColor="Black" BorderStyle="None" Font-Bold="True" Font-Size="35px" Width="542px" ForeColor="Navy" CssClass="auto-style3" Height="69px"></asp:Label>
</div>
    <div align="center">
     <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="flight_id" ShowFooter="True"   AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDataBound="RowDataBound" OnRowCancelingEdit="Flight_Row_CancleEditing" OnRowDeleting="Flight_Row_Deliting" OnRowEditing="Flight_Row_Editing" OnRowUpdating="Flight_Row_Updating" CssClass="myGridStyle" HeaderStyle-BackColor="Aqua" Width="1313px" Height="264px">
            <Columns>

                <asp:TemplateField  HeaderText="Airline Name">
                     <ItemTemplate>
                         <asp:Label ID="lblairlineName" runat="server" Text='<%# Eval("airline_name") %>'></asp:Label>
                      </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlAN" runat="server" CssClass="Txtstyle4"></asp:DropDownList>
                    </EditItemTemplate>
                    <FooterTemplate>
                            <asp:DropDownList ID="ddlairlineName" runat="server" CssClass="Txtstyle4"></asp:DropDownList>
                     </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Flight ID">
                    <ItemTemplate>
                        <%# Eval("flight_id") %> 
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Flight Name">
                    <ItemTemplate>
                        <%# Eval("flight_name") %>
                    </ItemTemplate>
                    <EditItemTemplate>
                       <asp:TextBox ID="txtFlightName" runat="server" Text='<%# Bind("flight_name") %>' CssClass="Txtstyle4"></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtFN" runat="server" CssClass="Txtstyle4"/>
                    </FooterTemplate>
                  </asp:TemplateField>

                <asp:TemplateField  HeaderText="Flight Source Location">
                     <ItemTemplate>
                        <%# Eval("f_source_location") %>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlSL" runat="server" CssClass="Txtstyle4"></asp:DropDownList>
                        <%--Text='<%# Bind("f_source_location") %>'--%>
                    </EditItemTemplate>
                    <FooterTemplate>
                            <asp:DropDownList ID="ddlSourceLocation" runat="server" CssClass="Txtstyle4"></asp:DropDownList>
                     </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField  HeaderText="Flight Source Location">
                    <ItemTemplate>
                        <%# Eval("f_destination_location") %>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddlDL" runat="server" CssClass="Txtstyle4" ></asp:DropDownList>
                       <%-- Text='<%# Bind("f_destination_location") %>'--%>
                    </EditItemTemplate>
                    <FooterTemplate>
                            <asp:DropDownList ID="ddlDestiLocation" runat="server" CssClass="Txtstyle4"></asp:DropDownList>
                     </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Departual Date">
                     <ItemTemplate>
                         <asp:Label id="lbldepardate" runat="server" Text='<%# Eval("f_departure_date","{0:dd/MM/yyyy }") %>'></asp:Label>
                       </ItemTemplate>
                    <EditItemTemplate>
                       <asp:TextBox ID="txtDepartualDate" runat="server" Text='<%# Bind("f_departure_date") %>' CssClass="Txtstyle4"></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtDD" runat="server" TextMode="Date" CssClass="Txtstyle4"/>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Arrival Date">
                     <ItemTemplate>
                         <asp:Label id="lblArrival" runat="server" Text='<%# Eval("f_arrival_date","{0:dd/MM/yyyy }") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                       <asp:TextBox ID="txtArrivalDate" runat="server" Text='<%# Bind("f_arrival_date") %>' CssClass="Txtstyle4"></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtAD" runat="server" TextMode="Date" CssClass="Txtstyle4"/>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText=" Ticket Price">
                     <ItemTemplate>
                       <%# Eval("ticket_price") %> 
                    </ItemTemplate>
                    <EditItemTemplate>
                       <asp:TextBox ID="txtTicketPrice" runat="server" Text='<%# Bind("ticket_price") %>' CssClass="Txtstyle4"></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtTP" runat="server" CssClass="Txtstyle4"/>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Flight Tax">
                     <ItemTemplate>
                       <%# Eval("flight_tax") %> 
                    </ItemTemplate>
                    <EditItemTemplate>
                       <asp:TextBox ID="txtFlightTax" runat="server" Text='<%# Bind("flight_tax") %>' CssClass="Txtstyle4"></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtFTax" runat="server" CssClass="Txtstyle4"/>
                    </FooterTemplate>
                </asp:TemplateField>


                <asp:TemplateField>
                    <FooterTemplate>
                        <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" ControlStyle-CssClass="button" ControlStyle-Font-Bold="true" ControlStyle-BorderColor="Highlight" ControlStyle-BackColor="Highlight" ControlStyle-ForeColor="White"/>
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
         </div>
</asp:Content>
