<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="AddLocationPage.aspx.cs" Inherits="Web_Flight_Reservation_System.AddLocationPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="CSS/Gridview.css" rel="stylesheet" />
    <link href="CSS/Button.css" rel="stylesheet" />
    <link href="CSS/Textbox.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   <div></div>
    <div align="center">
        <asp:Label ID="lblLocation" runat="server" Text="Add Location" BorderColor="Black" BorderStyle="None" Font-Bold="True" Font-Size="35px" Width="628px" ForeColor="Navy" CssClass="auto-style3" Height="69px"></asp:Label>
</div>
    <div>
        <asp:GridView ID="GridviewLocation" runat="server" DataKeyNames="location_id" ShowFooter="true" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDataBound="LocationRowDataBound" OnSelectedIndexChanged="GridviewLocation_SelectedIndexChanged" OnRowCancelingEdit="Location_Row_CancleEdit" OnRowDeleting="Location_Row_Deleting" OnRowEditing="location_Row_Editing" OnRowUpdating="location_RowUpdating" CssClass="myGridStyle" HeaderStyle-BackColor="Aqua" align="center">
            <Columns>
                 <asp:TemplateField HeaderText="Location ID">
                    <ItemTemplate>
                        <%# Eval("location_id") %> 
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Location Name">
                    <ItemTemplate>
                        <%# Eval("location_name") %>
                    </ItemTemplate>
                    <EditItemTemplate>
                       <asp:TextBox ID="txtLocationName" runat="server" Text='<%# Bind("location_name") %>' CssClass="Txtstyle4"></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="txtLN" runat="server"/>
                    </FooterTemplate>
                  </asp:TemplateField>
                <asp:TemplateField>
                    <FooterTemplate>
                        <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" ControlStyle-CssClass="button" ControlStyle-Font-Bold="true" ControlStyle-BorderColor="Highlight" ControlStyle-BackColor="Highlight" ControlStyle-ForeColor="White"/>
                    </FooterTemplate>
                </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
</asp:Content>
